include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/856dc00a017ae22617d188b4a952bba7d3ec943b/templates/ci-fairy.yml'

stages:
  - sanity check
  - build
  - check

# https://docs.gitlab.com/ee/ci/yaml/README.html#switch-between-branch-pipelines-and-merge-request-pipelines
# if a MR is opened: run a detached MR pipeline
# if not, run a regular pipeline
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

#
# Verify that commit messages are as expected, signed-off, etc.
#
check-commit:
  extends:
    - .fdo.ci-fairy
  stage: sanity check
  script:
    - ci-fairy check-commits --branch $CI_DEFAULT_BRANCH --signed-off-by --junit-xml=results.xml
  except:
    - main@redhat/rhel/src/kernel/documentation
  variables:
    GIT_DEPTH: 100
  artifacts:
    reports:
      junit: results.xml

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:alpine3.12
  stage: build
  before_script:
    - apk add make
  script:
    - cd scripts
    - make
  artifacts:
    paths:
      - scripts/RHMAINTAINERS_parser
      - scripts/yaml2CODEOWNERS
      - scripts/yaml2RHMAINTAINERS

check:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine:latest
  stage: check
  needs:
    - build
  before_script:
    - apk add git
  script:
    # rebuild the current files
    - ./scripts/yaml2CODEOWNERS info/owners.yaml > info/CODEOWNERS
    - ./scripts/yaml2RHMAINTAINERS info/owners.yaml > info/RHMAINTAINERS

    # clean up cache
    - rm -f .failed

    # check that the committed files matched
    - git diff --exit-code || touch .failed
    - |
      if [[ -e .failed ]]
      then
        echo '-----------------------------------------------------------------'
        echo ''
        echo ' Looks like the files scripts/CODEOWNERS or scripts/RHMAINTAINERS'
        echo ' have not been regenerated and checked in this commit.'
        echo ''
        echo ' Please run the following command before committing:'
        echo '        ./scripts/yaml2CODEOWNERS info/owners.yaml > info/CODEOWNERS'
        echo '        ./scripts/yaml2RHMAINTAINERS info/owners.yaml > info/RHMAINTAINERS'
        echo ''
        echo '-----------------------------------------------------------------'
        exit 1
      fi
